FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Excluir(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();

            bo.Excluir(id);

            return Json("Cadastro Excluido com sucesso");
        }

        [HttpPost]
        public JsonResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();
            
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (bo.VerificarExistencia(model.CPF))
                {
                    Response.StatusCode = 400;
                    return Json("CPF informado já possui cadastro ativo!");
                }
                
                model.Id = bo.Incluir(new Beneficiario()
                {                    
                    IdCliente = model.IdCliente,
                    Nome = model.Nome,
                    CPF = model.CPF
                });

                Response.StatusCode = 200;
                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public JsonResult Alterar(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();
       
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (bo.VerificarExistencia(model.CPF, model.Id))
                {
                    Response.StatusCode = 400;
                    return Json("CPF informado já possui cadastro ativo!");
                }

                bo.Alterar(new Beneficiario()
                {
                    Id = model.Id,
                    Nome = model.Nome,
                    IdCliente = model.IdCliente,
                    CPF = model.CPF
                });
                               
                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            Beneficiario cliente = bo.Consultar(id);
            Models.BeneficiarioModel model = null;

            if (cliente != null)
            {
                model = new BeneficiarioModel()
                {
                    Id = cliente.Id,
                    Nome = cliente.Nome,
                    CPF = cliente.CPF
                };

            
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult Consultar(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            Beneficiario beneficiario = bo.Consultar(id);
            Models.BeneficiarioModel model = null;

            if (beneficiario != null)
            {
                model = new BeneficiarioModel()
                {
                    Id = beneficiario.Id,
                    Nome = beneficiario.Nome,
                    CPF = beneficiario.CPF,
                    IdCliente = beneficiario.IdCliente
                };

                return Json(beneficiario);
            }
            else { 
                Response.StatusCode = 404;
                return Json("");
            }
        }

        [HttpPost]
        public JsonResult BeneficiarioList(int idCliente = 0)
        {
            try
            {
                List<Beneficiario> beneficiarios = new BoBeneficiario().Listar(idCliente);

                //Return result to jTable
                return Json(new { Result = "OK", Records = beneficiarios });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Beneficiario/Forms.cshtml
@{
    var isFormCreate = Model.IdCliente == 0;
}

@model WebAtividadeEntrevista.Models.BeneficiarioModel

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title fs-5" id="exampleModalLabel">Beneficiários</h3>
                <button type="button" class="close" data-dismiss="modal" style="position: relative; top: -25px;" aria-label="Close">×</button>
            </div>
            <div class="modal-body">
                <form id="formBenef">
                    <div class="row" style="display:flex">
                        @Html.HiddenFor(model => model.IdCliente)
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="CPF">CPF:</label>
                                <input required="required" type="text" class="form-control" id="CPF" name="CPF" placeholder="Ex.: 999.999.999-99" mask="999.999.999-99" maxlength="14">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label for="Nome">Nome:</label>
                                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
                            </div>
                        </div>
                        <div class="col-md-3" style="align-content: center; top: 5px;">
                            <button id="SalvaBenef" type="submit" class="btn btn-sm btn-primary">Incluir</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <table id="gridBeneficiarios" class="table"></table>
            </div>
        </div>
    </div>
</div>

<script>
    var urlAlteracaoBeneficiario = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
    var urlConsultaBeneficiario= '@Url.Action("Consultar", "Beneficiario", new { area = "" })';
    var urlBeneficiarioList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';
    var urlPostBeneficiario = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
    var urlExcluirBeneficiario = '@Url.Action("Excluir", "Beneficiario", new { area = "" })';
</script>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jtable")
@if (isFormCreate)
{
    @Scripts.Render("~/Scripts/Beneficiarios/FI.BeneficiariosCreate.js")
}
else
{
    @Scripts.Render("~/Scripts/Beneficiarios/FI.BeneficiariosEdit.js")
}